version: '3.5'

services:
  back:
    build: docker/back
    env_file:
      - .env
    ports:
      - ${HTTPD_BACK_PORT}:8080
    volumes:
      - ./docker/back/host.conf:/etc/nginx/sites-enabled/default
      - ./app:/var/www/portfolio/:delegated
    working_dir: /var/www/portfolio/
    depends_on:
      - php-fpm

  php-fpm:
    build: docker/php-fpm
    env_file:
      - .env
    ports:
      - ${PHP_FPM_PORT}:9000
    volumes:
      - ./app:/var/www/portfolio/:delegated
      - ./docker/php-fpm/fpm-pool.conf:/etc/php/7.1/fpm/pool.d/www.conf:ro
    working_dir: /var/www/portfolio/
    entrypoint: /docker-entrypoint.sh

  db:
    build: docker/postgre
    ports:
      - 5432:5432
    environment:
      - DB_USER=${PG_USER}
      - DB_NAME=${PG_DATABASE}
      - DB_PASS=${PG_PASSWORD}
      - PG_PASSWORD=root

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./docker/pgadmin/servers.json:/pgadmin4/servers.json
    ports:
      - ${PG_ADMIN_PORT}:80
    depends_on:
      - db
