security:
    encoders:
        App\Entity\AdminUser:
            algorithm: auto

    providers:
        users:
            entity:
                class: SecurityBundle:User
                property: 'username'
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\AdminUser
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        back-office:
            pattern: ^/admin/
            provider: app_user_provider
            form_login:
                login_path: login
                check_path: login
                default_target_path: dashboard
                always_use_default_target_path: true
                csrf_token_generator: security.csrf.token_manager
        main:
            anonymous: true
            lazy: true
            logout: ~

    access_control:
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
